### ISSUE TITLE
Sketches

### ISSUE THREAD

**Issue by DiiamEn** [1601-mma2013/Checked#1]
This is the sketch for the product.

**Comment by DiiamEn** [comment]
![14466875_1116928055068234_1049655649_o](https://cloud.githubusercontent.com/assets/20339755/18885079/af145e7c-851c-11e6-8102-25c3e982e091.jpg)

**Comment by LimChuChin** [comment]
![flow](https://cloud.githubusercontent.com/assets/20280931/18897944/ee73e17a-8560-11e6-96e5-47cd21f8071a.png)

**Comment by LimChuChin** [comment]
![flow](https://cloud.githubusercontent.com/assets/20280931/18898335/a3217c48-8563-11e6-97bb-1ce825b521b0.png)
